# Generated by Django 4.1.3 on 2022-12-01 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentcup',
            name='final',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournamentcup',
            name='inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
