# Generated by Django 4.1.3 on 2022-12-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentcup_created_tournamentcup_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('C', 'Copa'), ('L', 'Liga'), ('M', 'Mix')], max_length=5)),
                ('premio', models.CharField(max_length=20)),
                ('couta', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('inicio', models.DateTimeField(null=True)),
                ('final', models.DateTimeField(null=True)),
                ('numero', models.SmallIntegerField(default=8)),
            ],
        ),
        migrations.DeleteModel(
            name='TournamentCup',
        ),
    ]
