# Generated by Django 4.1.3 on 2022-12-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournaments_delete_tournamentcup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournaments',
            new_name='Tournament',
        ),
    ]
