# Generated by Django 4.1.3 on 2022-11-30 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=30)),
                ('indice', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=12)),
                ('serial', models.CharField(max_length=6)),
                ('frase', models.TextField(blank=True)),
                ('telefono', models.CharField(max_length=15)),
                ('tag', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('activo', models.BooleanField(default=False)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.league')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
