# Generated by Django 4.1.3 on 2022-11-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
